# Generated by Django 3.2.20 on 2024-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('idfeedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
