# Generated by Django 3.2.20 on 2024-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignManager',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'assign_manager',
                'managed': False,
            },
        ),
    ]
