# Generated by Django 3.2.23 on 2024-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=60)),
                ('e_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'slot',
                'managed': False,
            },
        ),
    ]
