# Generated by Django 3.2.20 on 2024-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('turf_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('turf_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('categoty', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'turf',
                'managed': False,
            },
        ),
    ]
